"""Add receipt-ticket relationship

Revision ID: abe3836ae318
Revises: 
Create Date: 2025-04-09 08:50:29.594383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe3836ae318'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('receipt_id_ticket_fkey', 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'id_ticket')
    op.create_foreign_key(None, 'seat_status', 'room', ['id_room'], ['id_room'])
    op.add_column('ticket', sa.Column('receipt_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ticket', 'receipt', ['receipt_id'], ['id_receipt'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'receipt_id')
    op.drop_constraint(None, 'seat_status', type_='foreignkey')
    op.add_column('receipt', sa.Column('id_ticket', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('receipt_id_ticket_fkey', 'receipt', 'ticket', ['id_ticket'], ['id_ticket'], onupdate='CASCADE')
    # ### end Alembic commands ###
